/*
 * Generates the lighter catalogs in src/data/lite/<level>/ from the full catalogs in src/data.
 *
 *   node scripts/build-lite.mjs [level ...]
 *
 * Land (provinces + counties) and sea (islands + water) are each simplified as one topology so shared borders stay
 * shared. Output paths use compact relative SVG path data (`M x y l dx dy ... z`), directly usable as a `d` attribute.
 * Ids, names, codes, label anchors and every other field are copied unchanged.
 */
import { createRequire } from 'node:module'
import path from 'node:path'
import { gzipSync } from 'node:zlib'
import { simplifyLayers, roundRings, ringsToRelativePath, pathToRings } from './lite/geometry.mjs'

const require = createRequire(import.meta.url)
const { readDataModule, writeDataModule } = require('./lib/data-module.cjs')

const root = path.resolve(import.meta.dirname, '..')
const dataDir = path.join(root, 'src/data')

/**
 * minWeight: smallest effective triangle area (SVG units squared; 1 unit is about 2 km) a vertex must span to be kept.
 * precision: decimals kept (0.01 units is about 20 m, 0.1 units about 200 m).
 * minRingArea: rings smaller than this (units squared) are dropped, except a feature's largest ring.
 */
export const levels = {
  standard: { precision: 2, land: { minWeight: 0.005, minRingArea: 0 }, sea: { minWeight: 0.01, minRingArea: 0.25 } },
  lite: { precision: 1, land: { minWeight: 0.03, minRingArea: 0.02 }, sea: { minWeight: 0.1, minRingArea: 0.5 } },
  mini: { precision: 1, land: { minWeight: 0.3, minRingArea: 0.1 }, sea: { minWeight: 0.5, minRingArea: 2 } },
}

const banners = {}
const load = (file, exportName, typeName) => {
  const source = require('node:fs').readFileSync(path.join(dataDir, file), 'utf8')
  banners[file] = source.slice(0, source.indexOf('import type'))
  return readDataModule(path.join(dataDir, file), exportName, typeName)
}

const ringArea = (ring) => {
  let area = 0
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++)
    area += (ring[j][0] + ring[i][0]) * (ring[j][1] - ring[i][1])
  return Math.abs(area / 2)
}

/** Re-encodes one feature; always keeps its largest ring so no feature (island, small county) disappears. */
const encode = (item, simplifiedRings, { precision, minRingArea }) => {
  const original = pathToRings(item.path)
  if (!original.length) return item.path
  let rings = roundRings(simplifiedRings, precision, minRingArea)
  if (!rings.length) {
    const largest = original.reduce((a, b) => (ringArea(b) > ringArea(a) ? b : a))
    rings = roundRings([largest], precision, 0)
  }
  return ringsToRelativePath(rings, precision)
}

const sizes = (value) => {
  const text = JSON.stringify(value)
  return { raw: text.length, gz: gzipSync(text, { level: 9 }).length }
}

export const buildLevels = (names) => {
  const full = {
    provinces: load('provinces.ts', 'provinceBoundaries', 'MapBoundary'),
    counties: load('counties.ts', 'countyBoundaries', 'MapBoundary'),
    islands: load('islands.ts', 'iranIslands', 'IranMapIsland'),
    water: load('water.ts', 'iranWaterBodies', 'IranMapWaterBody'),
  }
  const report = { full: Object.fromEntries(Object.entries(full).map(([k, v]) => [k, sizes(v)])) }
  for (const name of names) {
    const config = levels[name]
    if (!config) throw new Error(`Unknown level ${name}; known: ${Object.keys(levels).join(', ')}`)
    const land = simplifyLayers({ provinces: full.provinces, counties: full.counties }, config.land)
    const sea = simplifyLayers({ islands: full.islands, water: full.water }, config.sea)
    const out = {}
    for (const [layer, items, simplified, options] of [
      ['provinces', full.provinces, land.provinces, config.land],
      ['counties', full.counties, land.counties, config.land],
      ['islands', full.islands, sea.islands, config.sea],
      ['water', full.water, sea.water, config.sea],
    ]) {
      // Island and water rings follow the same rule; islands are never dropped (largest-ring fallback).
      out[layer] = items.map((item) => ({
        ...item,
        path: encode(item, simplified.get(item.id) || [], {
          precision: config.precision,
          minRingArea: options.minRingArea,
        }),
      }))
    }
    const dir = path.join(dataDir, 'lite', name)
    const files = [
      ['provinces.ts', banners['provinces.ts'], 'MapBoundary', 'provinceBoundaries', out.provinces],
      ['counties.ts', banners['counties.ts'], 'MapBoundary', 'countyBoundaries', out.counties],
      ['islands.ts', banners['islands.ts'], 'IranMapIsland', 'iranIslands', out.islands],
      ['water.ts', banners['water.ts'], 'IranMapWaterBody', 'iranWaterBodies', out.water],
    ]
    for (const [file, banner, typeName, exportName, value] of files) {
      const header = `${banner}// Simplified "${name}" level generated by scripts/build-lite.mjs from the full catalog.\n`
      writeDataModule({
        file: path.join(dir, file),
        banner: header,
        typeName,
        exportName,
        value,
        typeImport: '../../../interfaces.js',
      })
    }
    report[name] = Object.fromEntries(Object.entries(out).map(([k, v]) => [k, sizes(v)]))
  }
  return report
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const names = process.argv.slice(2)
  const report = buildLevels(names.length ? names : Object.keys(levels))
  const kb = (n) => (n / 1024).toFixed(1)
  const rows = []
  for (const [level, layers] of Object.entries(report)) {
    for (const [layer, { raw, gz }] of Object.entries(layers)) rows.push({ level, layer, rawKB: kb(raw), gzKB: kb(gz) })
  }
  console.table(rows)
}
